src/Entity/Personnes.php
<?php

namespace App\Entity;

use App\Repository\PersonnesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PersonnesRepository::class)
 */
class Personnes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profession;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cvpdf;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $apropos;

    /**
     * @ORM\Column(type="integer")
     */
    private $Age;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $langues;

    /**
     * @ORM\OneToMany(targetEntity=Email::class, mappedBy="personnes", orphanRemoval=true)
     */
    private $emails;

    /**
     * @ORM\OneToMany(targetEntity=Competencesprog::class, mappedBy="personne", orphanRemoval=true)
     */
    private $competencesprogs;

    /**
     * @ORM\OneToMany(targetEntity=Reseaux::class, mappedBy="personne", orphanRemoval=true)
     */
    private $reseauxes;

    /**
     * @ORM\OneToMany(targetEntity=CompetencesData::class, mappedBy="personne", orphanRemoval=true)
     */
    private $competencesData;

    /**
     * @ORM\OneToMany(targetEntity=Experiences::class, mappedBy="personne", orphanRemoval=true)
     */
    private $experiences;

    /**
     * @ORM\OneToMany(targetEntity=Diplomes::class, mappedBy="personne", orphanRemoval=true)
     */
    private $diplomes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $portrait;

    public function __construct()
    {
        $this->emails = new ArrayCollection();
        $this->competencesprogs = new ArrayCollection();
        $this->reseauxes = new ArrayCollection();
        $this->competencesData = new ArrayCollection();
        $this->experiences = new ArrayCollection();
        $this->diplomes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(string $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    public function getCvpdf(): ?string
    {
        return $this->cvpdf;
    }

    public function setCvpdf(string $cvpdf): self
    {
        $this->cvpdf = $cvpdf;

        return $this;
    }

    public function getApropos(): ?string
    {
        return $this->apropos;
    }

    public function setApropos(string $apropos): self
    {
        $this->apropos = $apropos;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getLangues(): ?string
    {
        return $this->langues;
    }

    public function setLangues(string $langues): self
    {
        $this->langues = $langues;

        return $this;
    }

    /**
     * @return Collection|Email[]
     */
    public function getEmails(): Collection
    {
        return $this->emails;
    }

    public function addEmail(Email $email): self
    {
        if (!$this->emails->contains($email)) {
            $this->emails[] = $email;
            $email->setPersonnes($this);
        }

        return $this;
    }

    public function removeEmail(Email $email): self
    {
        if ($this->emails->contains($email)) {
            $this->emails->removeElement($email);
            // set the owning side to null (unless already changed)
            if ($email->getPersonnes() === $this) {
                $email->setPersonnes(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Competencesprog[]
     */
    public function getCompetencesprogs(): Collection
    {
        return $this->competencesprogs;
    }

    public function addCompetencesprog(Competencesprog $competencesprog): self
    {
        if (!$this->competencesprogs->contains($competencesprog)) {
            $this->competencesprogs[] = $competencesprog;
            $competencesprog->setPersonne($this);
        }

        return $this;
    }

    public function removeCompetencesprog(Competencesprog $competencesprog): self
    {
        if ($this->competencesprogs->contains($competencesprog)) {
            $this->competencesprogs->removeElement($competencesprog);
            // set the owning side to null (unless already changed)
            if ($competencesprog->getPersonne() === $this) {
                $competencesprog->setPersonne(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reseaux[]
     */
    public function getReseauxes(): Collection
    {
        return $this->reseauxes;
    }

    public function addReseaux(Reseaux $reseaux): self
    {
        if (!$this->reseauxes->contains($reseaux)) {
            $this->reseauxes[] = $reseaux;
            $reseaux->setPersonne($this);
        }

        return $this;
    }

    public function removeReseaux(Reseaux $reseaux): self
    {
        if ($this->reseauxes->contains($reseaux)) {
            $this->reseauxes->removeElement($reseaux);
            // set the owning side to null (unless already changed)
            if ($reseaux->getPersonne() === $this) {
                $reseaux->setPersonne(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|CompetencesData[]
     */
    public function getCompetencesData(): Collection
    {
        return $this->competencesData;
    }

    public function addCompetencesData(CompetencesData $competencesData): self
    {
        if (!$this->competencesData->contains($competencesData)) {
            $this->competencesData[] = $competencesData;
            $competencesData->setPersonne($this);
        }

        return $this;
    }

    public function removeCompetencesData(CompetencesData $competencesData): self
    {
        if ($this->competencesData->contains($competencesData)) {
            $this->competencesData->removeElement($competencesData);
            // set the owning side to null (unless already changed)
            if ($competencesData->getPersonne() === $this) {
                $competencesData->setPersonne(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Experiences[]
     */
    public function getExperiences(): Collection
    {
        return $this->experiences;
    }

    public function addExperience(Experiences $experience): self
    {
        if (!$this->experiences->contains($experience)) {
            $this->experiences[] = $experience;
            $experience->setPersonne($this);
        }

        return $this;
    }

    public function removeExperience(Experiences $experience): self
    {
        if ($this->experiences->contains($experience)) {
            $this->experiences->removeElement($experience);
            // set the owning side to null (unless already changed)
            if ($experience->getPersonne() === $this) {
                $experience->setPersonne(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Diplomes[]
     */
    public function getDiplomes(): Collection
    {
        return $this->diplomes;
    }

    public function addDiplome(Diplomes $diplome): self
    {
        if (!$this->diplomes->contains($diplome)) {
            $this->diplomes[] = $diplome;
            $diplome->setPersonne($this);
        }

        return $this;
    }

    public function removeDiplome(Diplomes $diplome): self
    {
        if ($this->diplomes->contains($diplome)) {
            $this->diplomes->removeElement($diplome);
            // set the owning side to null (unless already changed)
            if ($diplome->getPersonne() === $this) {
                $diplome->setPersonne(null);
            }
        }

        return $this;
    }

    public function getPortrait(): ?string
    {
        return $this->portrait;
    }

    public function setPortrait(string $portrait): self
    {
        $this->portrait = $portrait;

        return $this;
    }
}

src/Form/PersonnesType.php
<?php

namespace App\Form;

use App\Entity\Personnes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonnesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('profession')
            ->add('cvpdf',FileType::class, array('data_class' => null,'required' => false))
            ->add('apropos',TextType::class)
            ->add('Age',IntegerType::class)
            ->add('email',EmailType::class)
            ->add('telephone')
            ->add('adresse')
            ->add('langues')
            ->add('portrait',FileType::class, array('data_class' => null,'required' => false))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Personnes::class,
        ]);
    }
}

src/Controller/PersonnesController.php
<?php

namespace App\Controller;

use App\Entity\Personnes;
use App\Form\PersonnesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class PersonnesController extends AbstractController
{
    /**
     * @Route("/personnes/{id}", name="personnes")
     */
    public function index(Personnes $personnes)
    {
        return $this->render('personnes/index.html.twig', [
            'personne' => $personnes ,
        ]);
    }
    /**
     * @Route("/add", name="add_personne")
     * @Route("/personnes/{id}/edit", name="edit_personne")
     */
    public function add(Personnes $personne=null,Request $request)
    {
        if(!$personne){
            $personne=new Personnes();
        }
        $formulaire=$this->createForm(PersonnesType::class,$personne);
        $formulaire->handleRequest($request);
        if($formulaire->isSubmitted() && $formulaire->isValid()){
            $brochureFile = $formulaire ['cvpdf']->getData();
            $originalFilename = pathinfo($brochureFile->getClientOriginalName(), PATHINFO_FILENAME);
            $newFilename = 'fichier-'.uniqid().'.'.$brochureFile->guessExtension();
            try {
                $brochureFile->move(
                    $this->getParameter('logo_directory'),
                    $newFilename
                );
            } catch (FileException $e) {

            }
            #####################
            $brochureFile = $formulaire ['portrait']->getData();
            $originalFilename = pathinfo($brochureFile->getClientOriginalName(), PATHINFO_FILENAME);
            $newportrait = 'fichier-'.uniqid().'.'.$brochureFile->guessExtension();
            try {
                $brochureFile->move(
                    $this->getParameter('logo_directory'),
                    $newportrait
                );
            } catch (FileException $e) {

            }
            $personne=$formulaire->getData();
            $personne->setCvpdf($newFilename);
            $personne->setPortrait($newportrait);
            $entityManager=$this->getDoctrine()->getManager();
            $entityManager->persist($personne);
            $entityManager->flush();
            unset($entityManager);
            unset($personne);
            return $this->redirectToRoute('listes_personne');
        }
        return $this->render('personnes/add.html.twig', [
            'formulaire' => $formulaire->createView()
        ]);
    }
}

templates/personnes/add.html.twig
{% extends 'base.add.html.twig' %}

{% block title %}
    WELCOME
{% endblock %}
{% block stylesheets %}
    <meta name="robots" content="Currently in 2nd year of a Master's degree in Business Intelligence, I hold a Bachelor's degree in Computer Engineering. I am passionate about IT and constantly looking for new experiences. I have an interest in the fields of BI, data science and am considering a career in it."/>
    <meta name="publisher" content="Oscar mugiraneza">
    <meta name="author" content="Oscar mugiraneza">
    <meta name="keywords" content="mugiraneza, CSS, JavaScript,C#(ASP.NET),SQL SERVER,TRANSACT SQL,PLSQL,UML/MERISE,JAVA,PHP,SYMFONY,JQUERY,TYPESCRIPT,MYSQL,ANGULAR,POSTEGRE,LINUX,NODEJS">
    <meta name="description" content="Currently in 2nd year of a Master's degree in Business Intelligence, I hold a Bachelor's degree in Computer Engineering. I am passionate about IT and constantly looking for new experiences. I have an interest in the fields of BI, data science and am considering a career in it."/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{asset('css/aos.css')}}" rel="stylesheet">
    <link rel="icon" href="{{asset('favicon.ico')}}" />
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('styles/main.css')}}" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-173026432-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-173026432-1');
    </script>
{% endblock %}

{% block employe %}
    <div class="section" id="skill">
        <div class="container">
            <div class="card" data-aos="fade-up" data-aos-anchor-placement="top-bottom">
                <div class="card-body">
                    {{ form_start(formulaire) }}
                        <div class="row mb-3">
                            <div class="col">
                                {{form_widget(formulaire.nom, {'attr':{'placeholder': "Nom",'class':'form-control'}})}}
                            </div>
                            <div class="col">
                                {{form_widget(formulaire.prenom, {'attr':{'placeholder': "Prénom",'class':'form-control'}})}}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col">
                                {{form_widget(formulaire.apropos, {'attr':{'placeholder': "À propos",'class':'form-control'}})}}
                            </div>
                            <div class="col">
                                {{form_widget(formulaire.Age, {'attr':{'placeholder': "Age",'class':'form-control'}})}}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col">
                                {{form_widget(formulaire.email, {'attr':{'placeholder': "E-mail",'class':'form-control'}})}}
                            </div>
                            <div class="col">
                                {{form_widget(formulaire.telephone, {'attr':{'placeholder': "Telephone",'class':'form-control'}})}}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col">
                                {{form_widget(formulaire.adresse, {'attr':{'placeholder': "Adresse",'class':'form-control'}})}}
                            </div>
                            <div class="col">
                                {{form_widget(formulaire.langues, {'attr':{'placeholder': "Langues",'class':'form-control'}})}}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col">
                                {{form_widget(formulaire.profession, {'attr':{'placeholder': "Profession",'class':'form-control'}})}}
                            </div>
                        </div>
                        <div class="row mb-3">

                            <div class="col">
                                {{form_widget(formulaire.portrait, {'attr':{'placeholder': "Langues",'class':'form-control'}})}}
                            </div>
                            <div class="col">
                                {{form_widget(formulaire.cvpdf, {'attr':{'placeholder': "Nom",'class':'form-control'}})}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <button class="btn btn-primary" type="submit">Soumettre</button>
                            </div>
                        </div>
                    {{ form_end(formulaire) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/personnes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ personne.nom|upper ~' '~ personne.prenom|capitalize }}
{% endblock %}
{% block stylesheets %}
    <meta name="robots" content="Currently in 2nd year of a Master's degree in Business Intelligence, I hold a Bachelor's degree in Computer Engineering. I am passionate about IT and constantly looking for new experiences. I have an interest in the fields of BI, data science and am considering a career in it."/>
    <meta name="publisher" content="Oscar mugiraneza">
    <meta name="author" content="Oscar mugiraneza">
    <meta name="keywords" content="mugiraneza, CSS, JavaScript,C#(ASP.NET),SQL SERVER,TRANSACT SQL,PLSQL,UML/MERISE,JAVA,PHP,SYMFONY,JQUERY,TYPESCRIPT,MYSQL,ANGULAR,POSTEGRE,LINUX,NODEJS">
    <meta name="description" content="Currently in 2nd year of a Master's degree in Business Intelligence, I hold a Bachelor's degree in Computer Engineering. I am passionate about IT and constantly looking for new experiences. I have an interest in the fields of BI, data science and am considering a career in it."/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{asset('css/aos.css')}}" rel="stylesheet">
    <link rel="icon" href="{{asset('favicon.ico')}}" />
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('styles/main.css')}}" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-173026432-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-173026432-1');
    </script>
{% endblock %}
{% block nom %}
    {{ personne.nom|upper ~' '~ personne.prenom|upper}}
{% endblock %}
{% block profile %}
    <div class="page-header page-header-small" filter-color="green">
        <div class="page-header-image" data-parallax="true" style='background-image: url({{asset("images/cc-bg-1.jpg")}}'></div>
        <div class="container">
            <div class="content-center">
                <div class="cc-profile-image"><a href="#about" class="smooth-scroll"><img src="{{asset('uploads/logo/'~personne.portrait)}}" alt="Image"/></a></div>
                <div class="h2 title">{{ personne.nom|upper ~' '~ personne.prenom|capitalize }}</div>
                <p class="category text-white">{{personne.profession}}</p>
                <a class="btn btn-primary smooth-scroll mr-2" href="#contact" data-aos="zoom-in" data-aos-anchor="data-aos-anchor">Contactez-moi</a>
                <a class="btn btn-primary" href="{{asset('uploads/logo/'~personne.cvpdf)}}" target = "_blank" data-aos="zoom-in" data-aos-anchor="data-aos-anchor">Télécharger CV</a>
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="button-container">
                    {% for lien in personne.reseauxes %}
                        <a class="btn btn-default btn-round btn-lg btn-icon" href="{{ lien.lien}}" target = "_blank" rel="tooltip" title="{{ lien.libelle }}"><i class="{{ lien.icon }}"></i></a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block apropos %}
    <p>{{ personne.apropos }}</p>
    {#<p>Actuellement en 2e année d'un Master Informatique décisionnelle, je suis titulaire d'une licence en génie logiciel.</p>
    <p>Je suis passionné par l'informatique et constamment en quête de nouvelles expériences.</p>
    <p>J'ai un intérêt pour les domaines de la BI, la data science et envisage d'y faire carrière.</p>#}
{% endblock %}
{% block information %}
    <div class="h4 mt-0 title">Informations générales</div>
    <div class="row">
        <div class="col-sm-4"><strong class="text-uppercase">Age:</strong></div>
        <div class="col-sm-8">{{ personne.age }} ans</div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-4"><strong class="text-uppercase">Email :</strong></div>
        <div class="col-sm-8">{{ personne.email}}</div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-4"><strong class="text-uppercase">Téléphone :</strong></div>
        <div class="col-sm-8">{{ personne.telephone}}</div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-4"><strong class="text-uppercase">Adresse :</strong></div>
        <div class="col-sm-8">{{ personne.adresse }}</div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-4"><strong class="text-uppercase">Languages :</strong></div>
        <div class="col-sm-8">{{ personne.langues }}</div>
    </div>
{% endblock %}
{% block competenceprog %}
    <div class="row">
        {% for connaissance in personne.competencesprogs %}
            <div class="col-md-6">
                <div class="progress-container progress-primary"><span class="progress-badge">{{ connaissance.libelle }}</span>
                    <div class="progress">
                        <div class="progress-bar progress-bar-primary" data-aos="progress-full" data-aos-offset="10" data-aos-duration="2000" role="progressbar" aria-valuenow="{{ connaissance.niveau }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ connaissance.niveau }}%;"></div><span class="progress-value">{{ connaissance.niveau }}%</span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block competencedata %}
    <div class="row">
        {% for connaissance in personne.competencesData %}
            <div class="col-md-6">
                <div class="progress-container progress-primary"><span class="progress-badge">{{ connaissance.libelle }}</span>
                    <div class="progress">
                        <div class="progress-bar progress-bar-primary" data-aos="progress-full" data-aos-offset="10" data-aos-duration="2000" role="progressbar" aria-valuenow="{{ connaissance.niveau }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ connaissance.niveau }}%;"></div><span class="progress-value">{{ connaissance.niveau }}%</span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block experienceprofessionnel %}
    {% for experience in personne.experiences %}
    <div class="card">
        <div class="row">
            <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
                <div class="card-body cc-experience-header">
                    <p>{{ experience.moisdebut~' '~experience.anneedebut~' – '~experience.moisfin~' '~experience.anneefin}}</p>
                    <div class="h5">{{experience.entreprise}}</div>
                </div>
            </div>
            <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
                <div class="card-body">
                    <div class="h5">{{experience.libelle}}</div>
                    <p>{{experience.description}}</p>
                    {# <ul  class="">
                         <li class=""> Réalisation d'une analyse technique pour identifier les besoins du client</li>
                    </ul>#}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}
{% block diplomeformation %}
    {% for parcours in personne.diplomes %}
        <div class="card">
            <div class="row">
                <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
                    <div class="card-body cc-education-header">
                        <p>
                            {% if not parcours.anneefin %}
                                {{ 'Depuis '~parcours.moisdebut|lower ~' '~ parcours.anneedebut }}
                            {% else %}
                                {{ parcours.anneedebut~ '-'~parcours.anneefin }}
                            {% endif  %}
                        </p>
                        <div class="h5">{{ parcours.description }}</div>
                    </div>
                </div>
                <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
                    <div class="card-body">
                        <div class="h5">{{ parcours.libelle }}</div>
                        <p class="category">{{ parcours.entreprise|upper ~' '~ parcours.ville|upper }} </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}
{% block adresse %}
    <p class="mb-0"><strong>Adresse </strong></p>
    <p class="pb-2">{{ personne.adresse }}</p>
    <p class="mb-0"><strong>Téléphone</strong></p>
    <p class="pb-2">{{ personne.telephone }}</p>
    <p class="mb-0"><strong>E-mail</strong></p>
    <p>
    {% for mailes in personne.emails %}
        {{ mailes.libelle}}
    {% endfor %}
    </p>
{% endblock %}
{% block footer %}
    <div class="container text-center">
        {% for lien in personne.reseauxes %}
            <a class="{{ lien.styles}}" href="{{ lien.lien}}" target = "_blank"><i class="{{ lien.icon }} fa-2x " aria-hidden="true"></i></a>
        {% endfor %}
    </div>
    <div class="h4 title text-center">{{ personne.nom|upper ~' '~ personne.prenom|capitalize }}</div>
{% endblock %}